services:
  - type: web
    name: my-backend
    runtime: node
    repo: https://github.com/krish-wp/DumpIt-backend
    branch: main
    buildCommand: npm install
    startCommand: npm run dev
    plan: free
    region: oregon
    autoDeploy: true

    envVars:
      - key: PORT
        value: 8000
      - key: MONGODB_URL
        sync: false
      - key: CORS_ORIGIN
        value: '*'
      - key: GEMINI_API_KEY
        sync: false
